FROM alpine as base

WORKDIR /app

COPY --from=golang:1.19-alpine /usr/local/go/ /usr/local/go/
ENV PATH="$PATH:/usr/local/go/bin"
ENV PATH="$PATH:/root/go/bin"

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o ./transact ./cmd/transact/main.go

FROM base as transact
COPY --from=base /app/transact /bin/transact
CMD ["/bin/transact"]