FROM alpine as base

WORKDIR /app

COPY --from=golang:1.19-alpine /usr/local/go/ /usr/local/go/
ENV PATH="$PATH:/usr/local/go/bin"
ENV PATH="$PATH:/root/go/bin"

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o ./converter ./cmd/converter/main.go

FROM base as converter
COPY --from=base /app/converter /bin/converter
CMD ["/bin/converter"]





